-- Run this in the Supabase SQL editor.
-- It creates the wardrobe tables, row-level security policies, and the image bucket.

create table if not exists public.items (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  product_url text,
  memo text,
  parent_category text,
  category text,
  brand text,
  color text,
  image_url text,
  image_edit jsonb not null default '{}'::jsonb,
  size_label text,
  shoe_size text,
  retail_price integer,
  purchase_price integer,
  purchase_date date,
  owned boolean not null default true,
  rating integer check (rating is null or rating between 1 and 5),
  raw jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.items
  add column if not exists image_url text,
  add column if not exists image_edit jsonb not null default '{}'::jsonb,
  add column if not exists rating integer;

alter table public.items
  drop constraint if exists items_rating_range_check;

alter table public.items
  add constraint items_rating_range_check
  check (rating is null or rating between 1 and 5);

notify pgrst, 'reload schema';

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references auth.users(id) on delete cascade,
  parent_id uuid references public.categories(id) on delete cascade,
  name text not null,
  is_system boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.colors (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references auth.users(id) on delete cascade,
  name text not null,
  hex text,
  is_system boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.colors
  add column if not exists owner_id uuid references auth.users(id) on delete cascade,
  add column if not exists hex text,
  add column if not exists is_system boolean not null default false,
  add column if not exists sort_order integer not null default 0,
  add column if not exists created_at timestamptz not null default now();

create table if not exists public.measurement_definitions (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references auth.users(id) on delete cascade,
  key text,
  label_ko text not null,
  default_unit text not null default 'cm',
  is_system boolean not null default false,
  created_at timestamptz not null default now(),
  unique (owner_id, label_ko),
  unique (key)
);

create table if not exists public.category_measurement_templates (
  id bigint generated by default as identity primary key,
  category_name text not null,
  measurement_definition_id uuid not null references public.measurement_definitions(id) on delete cascade,
  importance text not null default 'recommended' check (importance in ('required', 'recommended', 'optional')),
  display_group text,
  sort_order integer not null default 0,
  unique (category_name, measurement_definition_id)
);

create table if not exists public.item_measurements (
  id bigint generated by default as identity primary key,
  item_id text not null references public.items(id) on delete cascade,
  measurement_definition_id uuid references public.measurement_definitions(id) on delete set null,
  custom_label text,
  label text not null,
  value numeric not null,
  value_text text,
  unit text not null default 'cm',
  source text not null default 'manual',
  source_name text,
  notes text,
  sort_order integer not null default 0,
  unique (item_id, label)
);

alter table public.item_measurements
  add column if not exists measurement_definition_id uuid references public.measurement_definitions(id) on delete set null,
  add column if not exists custom_label text,
  add column if not exists value_text text,
  add column if not exists source text not null default 'manual',
  add column if not exists source_name text,
  add column if not exists notes text,
  add column if not exists sort_order integer not null default 0;

create table if not exists public.item_images (
  id text primary key,
  item_id text not null references public.items(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  storage_provider text not null default 'supabase-storage',
  storage_bucket text not null default 'wardrobe-images',
  storage_path text not null unique,
  width integer,
  height integer,
  mime text,
  is_primary boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.item_images
  add column if not exists storage_provider text not null default 'supabase-storage',
  add column if not exists storage_bucket text not null default 'wardrobe-images';

create table if not exists public.share_snapshots (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  token text not null unique,
  payload jsonb not null,
  is_active boolean not null default true,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.account_deletion_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  requester_email text,
  status text not null default 'requested' check (status in ('requested', 'processing', 'completed', 'rejected', 'cancelled')),
  note text,
  requested_at timestamptz not null default now(),
  processed_at timestamptz
);

create index if not exists items_user_updated_idx on public.items (user_id, updated_at desc);
create index if not exists items_user_category_idx on public.items (user_id, parent_category, category);
create index if not exists items_user_rating_idx on public.items (user_id, rating) where rating is not null;
create index if not exists categories_owner_parent_idx on public.categories (owner_id, parent_id, sort_order, name);
create index if not exists categories_system_parent_idx on public.categories (parent_id, sort_order, name) where is_system = true;
create unique index if not exists colors_system_name_idx on public.colors (lower(name)) where is_system = true;
create unique index if not exists colors_owner_name_idx on public.colors (owner_id, lower(name)) where owner_id is not null;
create index if not exists colors_owner_sort_idx on public.colors (owner_id, sort_order, name);
create index if not exists measurement_definitions_owner_idx on public.measurement_definitions (owner_id, label_ko);
create index if not exists category_measurement_templates_category_idx on public.category_measurement_templates (category_name, sort_order);
create index if not exists item_measurements_item_idx on public.item_measurements (item_id);
create index if not exists item_measurements_definition_idx on public.item_measurements (measurement_definition_id);
create index if not exists item_images_item_idx on public.item_images (item_id);
create index if not exists item_images_storage_locator_idx on public.item_images (storage_provider, storage_bucket, storage_path);
create index if not exists share_snapshots_token_idx on public.share_snapshots (token) where is_active = true;
create index if not exists account_deletion_requests_user_idx on public.account_deletion_requests (user_id, requested_at desc);
create unique index if not exists account_deletion_requests_open_user_idx
  on public.account_deletion_requests (user_id)
  where status in ('requested', 'processing');

create or replace function public.touch_parent_item_updated_at()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_item_id text;
begin
  target_item_id := coalesce(new.item_id, old.item_id);

  if target_item_id is not null then
    update public.items
    set updated_at = now()
    where id = target_item_id;
  end if;

  return coalesce(new, old);
end;
$$;

drop trigger if exists touch_parent_item_from_measurements on public.item_measurements;
create trigger touch_parent_item_from_measurements
after insert or update or delete on public.item_measurements
for each row execute function public.touch_parent_item_updated_at();

drop trigger if exists touch_parent_item_from_images on public.item_images;
create trigger touch_parent_item_from_images
after insert or update or delete on public.item_images
for each row execute function public.touch_parent_item_updated_at();

alter table public.items enable row level security;
alter table public.categories enable row level security;
alter table public.colors enable row level security;
alter table public.measurement_definitions enable row level security;
alter table public.category_measurement_templates enable row level security;
alter table public.item_measurements enable row level security;
alter table public.item_images enable row level security;
alter table public.share_snapshots enable row level security;
alter table public.account_deletion_requests enable row level security;

drop policy if exists "items are owned by the current user" on public.items;
create policy "items are owned by the current user"
on public.items
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "system and owned categories are readable" on public.categories;
create policy "system and owned categories are readable"
on public.categories
for select
using (is_system = true or owner_id = auth.uid());

drop policy if exists "users manage custom categories" on public.categories;
create policy "users manage custom categories"
on public.categories
for all
using (owner_id = auth.uid())
with check (owner_id = auth.uid() and is_system = false);

drop policy if exists "system and owned colors are readable" on public.colors;
create policy "system and owned colors are readable"
on public.colors
for select
using (is_system = true or owner_id = auth.uid());

drop policy if exists "users manage custom colors" on public.colors;
create policy "users manage custom colors"
on public.colors
for all
using (owner_id = auth.uid())
with check (owner_id = auth.uid() and is_system = false);

drop policy if exists "system measurement definitions are readable" on public.measurement_definitions;
create policy "system measurement definitions are readable"
on public.measurement_definitions
for select
using (is_system = true or owner_id = auth.uid());

drop policy if exists "users manage custom measurement definitions" on public.measurement_definitions;
create policy "users manage custom measurement definitions"
on public.measurement_definitions
for all
using (owner_id = auth.uid())
with check (owner_id = auth.uid() and is_system = false);

drop policy if exists "category measurement templates are readable" on public.category_measurement_templates;
create policy "category measurement templates are readable"
on public.category_measurement_templates
for select
using (true);

drop policy if exists "measurements follow item ownership" on public.item_measurements;
create policy "measurements follow item ownership"
on public.item_measurements
for all
using (
  exists (
    select 1 from public.items
    where items.id = item_measurements.item_id
      and items.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.items
    where items.id = item_measurements.item_id
      and items.user_id = auth.uid()
  )
);

with parent_rows(name, sort_order) as (
  values
    ('상의', 10),
    ('하의', 20),
    ('아우터', 30),
    ('신발', 40),
    ('가방', 50),
    ('악세사리', 60)
)
insert into public.categories (name, is_system, sort_order)
select parent_rows.name, true, parent_rows.sort_order
from parent_rows
where not exists (
  select 1 from public.categories
  where categories.name = parent_rows.name
    and categories.parent_id is null
    and categories.is_system = true
);

with child_rows(parent_name, name, sort_order) as (
  values
    ('상의', '티셔츠 (긴팔)', 10), ('상의', '티셔츠 (반팔)', 20), ('상의', '셔츠 (긴팔)', 30), ('상의', '셔츠 (반팔)', 40),
    ('상의', '니트', 50), ('상의', '니트베스트', 60), ('상의', '가디건', 70), ('상의', '집업', 80), ('상의', '스웨트셔츠', 90), ('상의', '후디', 100),
    ('하의', '슬랙스', 10), ('하의', '치노/퍼티그', 20), ('하의', '데님', 30), ('하의', '린넨/나일론', 40), ('하의', '스웨트/코듀로이', 50), ('하의', '반바지', 60),
    ('아우터', '코트', 10), ('아우터', '블레이저', 20), ('아우터', '야상', 30), ('아우터', '재킷', 40), ('아우터', '바람막이/플리스', 50), ('아우터', '패딩', 60),
    ('신발', '스니커즈', 10), ('신발', '구두', 20), ('신발', '샌들', 30), ('신발', '부츠', 40),
    ('가방', '백팩', 10), ('가방', '크로스백', 20), ('가방', '토트백', 30),
    ('악세사리', '아이웨어', 10), ('악세사리', '모자', 20), ('악세사리', '벨트', 30), ('악세사리', '넥타이', 40),
    ('악세사리', '머플러/장갑', 50), ('악세사리', '시계/팔찌/반지', 60), ('악세사리', '지갑', 70)
)
insert into public.categories (parent_id, name, is_system, sort_order)
select parent.id, child_rows.name, true, child_rows.sort_order
from child_rows
join public.categories parent
  on parent.name = child_rows.parent_name
  and parent.parent_id is null
  and parent.is_system = true
where not exists (
  select 1 from public.categories child
  where child.name = child_rows.name
    and child.parent_id = parent.id
    and child.is_system = true
);

with color_rows(name, hex, sort_order) as (
  values
    ('블랙', '#202124', 10),
    ('화이트', '#ffffff', 20),
    ('브라운', '#795548', 30),
    ('베이지', '#d8c4a3', 40),
    ('네이비', '#243b64', 50),
    ('블루', '#1a73e8', 60),
    ('그레이/실버', '#c4c7c5', 70),
    ('그린', '#188038', 80),
    ('카키', '#7d8460', 90),
    ('레드', '#c5221f', 100),
    ('와인', '#7b1f32', 110),
    ('핑크', '#f4a6b8', 120),
    ('옐로우', '#fbbc04', 130),
    ('오렌지', '#f29900', 140),
    ('골드', '#c6a15b', 150)
)
insert into public.colors (name, hex, is_system, sort_order)
select color_rows.name, color_rows.hex, true, color_rows.sort_order
from color_rows
where not exists (
  select 1 from public.colors
  where lower(colors.name) = lower(color_rows.name)
    and colors.is_system = true
);

insert into public.measurement_definitions (key, label_ko, default_unit, is_system)
values
  ('total_length', '총장', 'cm', true),
  ('shoulder', '어깨', 'cm', true),
  ('chest', '가슴', 'cm', true),
  ('sleeve', '소매', 'cm', true),
  ('waist', '허리', 'cm', true),
  ('thigh', '허벅지', 'cm', true),
  ('rise', '밑위', 'cm', true),
  ('hem', '밑단', 'cm', true),
  ('width', '폭', 'cm', true),
  ('height', '높이', 'cm', true),
  ('temple_length', '다리길이', 'mm', true),
  ('circumference', '둘레길이', 'cm', true),
  ('lens_width', '렌즈길이', 'mm', true),
  ('bridge_width', '브릿지길이', 'mm', true),
  ('brim_length', '챙길이', 'cm', true)
on conflict (key) do update set
  label_ko = excluded.label_ko,
  default_unit = excluded.default_unit,
  is_system = excluded.is_system;

with template_rows(category_name, definition_key, sort_order) as (
  values
    ('상의', 'total_length', 10), ('상의', 'shoulder', 20), ('상의', 'chest', 30), ('상의', 'sleeve', 40),
    ('아우터', 'total_length', 10), ('아우터', 'shoulder', 20), ('아우터', 'chest', 30), ('아우터', 'sleeve', 40),
    ('하의', 'total_length', 10), ('하의', 'waist', 20), ('하의', 'rise', 30), ('하의', 'thigh', 40), ('하의', 'hem', 50),
    ('신발', 'height', 10), ('신발', 'width', 20),
    ('가방', 'height', 10), ('가방', 'width', 20),
    ('아이웨어', 'lens_width', 10), ('아이웨어', 'bridge_width', 20), ('아이웨어', 'temple_length', 30),
    ('모자', 'circumference', 10), ('모자', 'brim_length', 20), ('모자', 'height', 30),
    ('벨트', 'total_length', 10), ('벨트', 'width', 20),
    ('머플러/장갑', 'total_length', 10), ('머플러/장갑', 'width', 20),
    ('넥타이', 'total_length', 10), ('넥타이', 'width', 20),
    ('시계/팔찌/반지', 'width', 10), ('시계/팔찌/반지', 'height', 20),
    ('지갑', 'width', 10), ('지갑', 'height', 20)
)
insert into public.category_measurement_templates (category_name, measurement_definition_id, sort_order)
select template_rows.category_name, measurement_definitions.id, template_rows.sort_order
from template_rows
join public.measurement_definitions on measurement_definitions.key = template_rows.definition_key
on conflict (category_name, measurement_definition_id) do update set
  sort_order = excluded.sort_order;

update public.item_measurements
set
  measurement_definition_id = measurement_definitions.id,
  unit = coalesce(nullif(item_measurements.unit, ''), measurement_definitions.default_unit)
from public.measurement_definitions
where item_measurements.measurement_definition_id is null
  and item_measurements.label = measurement_definitions.label_ko;

update public.item_measurements
set custom_label = label
where measurement_definition_id is null
  and custom_label is null;

drop policy if exists "images are owned by the current user" on public.item_images;
create policy "images are owned by the current user"
on public.item_images
for all
using (
  auth.uid() = owner_id
  and exists (
    select 1 from public.items
    where items.id = item_images.item_id
      and items.user_id = auth.uid()
  )
)
with check (
  auth.uid() = owner_id
  and exists (
    select 1 from public.items
    where items.id = item_images.item_id
      and items.user_id = auth.uid()
  )
);

drop policy if exists "share snapshots can be managed by owners" on public.share_snapshots;
create policy "share snapshots can be managed by owners"
on public.share_snapshots
for all
using (auth.uid() = owner_id)
with check (auth.uid() = owner_id);

drop policy if exists "active share snapshots are readable" on public.share_snapshots;

drop policy if exists "users can read their account deletion requests" on public.account_deletion_requests;
create policy "users can read their account deletion requests"
on public.account_deletion_requests
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "users can create account deletion requests" on public.account_deletion_requests;
create policy "users can create account deletion requests"
on public.account_deletion_requests
for insert
to authenticated
with check ((select auth.uid()) = user_id and status = 'requested');

create or replace function public.get_share_snapshot(share_token text)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select payload
  from public.share_snapshots
  where token = share_token
    and is_active = true
    and (expires_at is null or expires_at > now())
  limit 1
$$;

revoke all on function public.get_share_snapshot(text) from public;
grant execute on function public.get_share_snapshot(text) to anon, authenticated;

do $$
begin
  if to_regclass('storage.buckets') is not null then
    insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
    values (
      'wardrobe-images',
      'wardrobe-images',
      false,
      5242880,
      array['image/webp', 'image/jpeg', 'image/png']
    )
    on conflict (id) do update set
      public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;
  else
    raise notice 'storage.buckets does not exist. Create the wardrobe-images bucket from Supabase Storage UI, then rerun this script.';
  end if;
end $$;

do $$
begin
  if to_regclass('storage.objects') is not null then
    execute 'drop policy if exists "users can read their wardrobe images" on storage.objects';
    execute 'create policy "users can read their wardrobe images"
      on storage.objects
      for select
      using (
        bucket_id = ''wardrobe-images''
        and (storage.foldername(name))[1] = auth.uid()::text
      )';

    execute 'drop policy if exists "users can upload their wardrobe images" on storage.objects';
    execute 'create policy "users can upload their wardrobe images"
      on storage.objects
      for insert
      with check (
        bucket_id = ''wardrobe-images''
        and (storage.foldername(name))[1] = auth.uid()::text
      )';

    execute 'drop policy if exists "users can update their wardrobe images" on storage.objects';
    execute 'create policy "users can update their wardrobe images"
      on storage.objects
      for update
      using (
        bucket_id = ''wardrobe-images''
        and (storage.foldername(name))[1] = auth.uid()::text
      )
      with check (
        bucket_id = ''wardrobe-images''
        and (storage.foldername(name))[1] = auth.uid()::text
      )';

    execute 'drop policy if exists "users can delete their wardrobe images" on storage.objects';
    execute 'create policy "users can delete their wardrobe images"
      on storage.objects
      for delete
      using (
        bucket_id = ''wardrobe-images''
        and (storage.foldername(name))[1] = auth.uid()::text
      )';
  else
    raise notice 'storage.objects does not exist. Storage policies were skipped.';
  end if;
end $$;
